version: '3.6'

services:
  discovery-service-app:
    image: discovery-service-img
    container_name: discovery-service-cn
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    logging:
      driver: json-file
    networks:
      - ms-all-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service-app:8761/eureka

  edge-service-app:
    image: edge-service-img
    container_name: edge-service-cn
    build:
      context: ./edge-service
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    logging:
      driver: json-file
    networks:
      - ms-all-network
    depends_on:
      - discovery-service-app
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service-app:8761/eureka
#    command: ["./wait-for.sh", "localhost:8761"]

  sample-client-app:
    image: sample-client-img
    container_name: sample-client-cn
    build:
      context: ./sample-client
      dockerfile: Dockerfile
    expose:
      - 8081
    logging:
      driver: json-file
    networks:
      - ms-all-network
    depends_on:
      - discovery-service-app
      - edge-service-app
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service-app:8761/eureka
#    command: ["./wait-for.sh", "localhost:8762"]

networks:
  ms-all-network:
    driver: bridge